@startuml
left to right direction
abstract class OutputAudio{
    - {static} sourcePort = 4080 : int
    - {static} socketOutgoing : DatagramSocket
    - {static} <i>volatile</i> active : boolean
    --
    + {static} boolean isRunning()
    + {static} void setRunning(boolean newValue)
    --
    + {static} void sendAudio(byte[] toSend)
}

class AudioThread{
    - {static} sourcePort = 4070 : int
    - {static} socketIncoming : DatagramSocket
    --
    + {static} DatagramSocket getSocketIncoming()
    --
    + @Override void run()
}

class AudioSinusoidalThread{
    - {static} FREQUENCY = 200 : double
    - {static} AMPLITUDE = 4000 : double
    - {static} TIME_INCREMENTATION = 5 : double
    --
    + {static} double getFrequency()
    + {static} double getAmplitude()
    + {static} double getTimeIncrementation()
    + {static} double setFrequency()
    + {static} double setAmplitude()
    + {static} double setTimeIncrementation()
    --
    + @Override void run()
}

class AudioFileThread{
    @ Override void run()
}

class RTPPacket{
}

AudioThread *-- OutputAudio
AudioSinusoidalThread *-- OutputAudio
AudioFileThread *-- OutputAudio
OutputAudio *-- RTPPacket

@enduml